env: 'dev'

app:
  name: 'hd-wallet-saas'
  version: '0.1.0-alpha'
  description: 'A SAAS for managing HD wallets service'
  environment: 'development'
  log-level: 'dev'

api-server:
  base-path: '/api'
  server-port: '8081'
  cors: true

database-config:
  host: 'localhost'
  port: 33062
  user: 'root'
  password: 'root'
  database-name: 'db_hd_wallet_saas'
  driver: 'mysql'
  driver-version: '8'

gorm:
  using-exist-db: false
  custom-gorm-cfg: true
